{{- range $key, $val := $.Values.catalogs }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  image: {{ $.Values.path }}/{{ $key }}:{{ $.Values.version }}
  sourceType: grpc
{{- end }}
