{{- range $key, $val := $.Values.catalogs }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
  name: {{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  image: {{ $.Values.path }}/registry.redhat.io/redhat/{{ $key }}:latest
  sourceType: grpc
{{- end }}
