{{- range $key, $val := $.Values.subscriptions }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $key }}
  namespace: {{ $val.namespace }}
spec:
  channel: {{ $val.channel }}
  installPlanApproval: Automatic
  name: {{ $key }}
  source: {{ $val.catalogSource }}
  sourceNamespace: {{ $.Values.catalogSourceNamespace }}
{{- end }}
