{{- range $catalog, $catval := $.Values.catalogs }}
{{- range $package, $pacval := $catval.packages }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $package }}
  namespace: {{ $pacval.namespace }}
spec:
  channel: {{ $pacval.channel }}
  installPlanApproval: Automatic
  name: {{ $package }}
  source: {{ $catalog }}
  sourceNamespace: {{ $.Values.namespace }}
{{- end }}
{{- end }}
